export default {
    notifications: require('./notifications.json'),
    posts: require('./posts.json'),
    curatorReviews: require('./curator-reviews.json'),
    products: require('./products.json'),
    collections: require('./collections.json'),
    assets: require('./assets.json'),
    projects: require('./projects.json'),
    realms: require('./realms.json'),
    profiles: require('./profiles.json'),
    updates: require('./updates.json'),
    wallets: require('./wallets.json'),
    gameSeries: require('./game-series.json'),
    ideas: require('./ideas.json'),
}
