http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: 'localhost'
    paths: '/api/v1/*'
serviceEndpoints:
  web:
    url: 'http://127.0.0.1:9001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    #  - key-auth:
      - proxy:
          - action:
              serviceEndpoint: web 
              changeOrigin: true
